//! Rendering the surface as a Luau module.

use std::fmt::Write as _;

use crate::ir::Surface;

/// The `React` module the generated file requires. Projects disagree about
/// where packages live, so the path is a parameter rather than a guess.
pub const DEFAULT_REQUIRE: &str = "ReplicatedStorage.Packages.React";

/// How the emitted body is indented.
///
/// This exists because a generated file a formatter wants to rewrite is a
/// recurring annoyance: the first `stylua` run produces a diff, and every later
/// refresh produces another. Matching the formatter is cheaper than fighting
/// it, so the default is `StyLua`'s own default rather than any one project's
/// taste.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Indent {
    /// `StyLua`'s default, and so the one most projects will already agree with.
    #[default]
    Tabs,
    /// Four spaces, for projects that set `indent_type = "Spaces"`.
    Spaces,
}

impl Indent {
    fn as_str(self) -> &'static str {
        match self {
            Indent::Tabs => "\t",
            Indent::Spaces => "    ",
        }
    }
}

#[derive(Debug, Clone)]
pub struct Style {
    pub require_path: String,
    pub indent: Indent,
}

impl Default for Style {
    fn default() -> Self {
        Self {
            require_path: DEFAULT_REQUIRE.to_owned(),
            indent: Indent::default(),
        }
    }
}

pub struct Emitted {
    pub source: String,
    pub classes: usize,
    pub properties: usize,
}

/// Why the indexer is here, in the file itself, so the next person to read the
/// output does not have to rediscover it.
///
/// Prose inside a block comment, which no formatter reindents, so these keep
/// their own leading spaces whatever the body uses.
const INDEXER_NOTE: &[&str] = &[
    "    Every prop accepts its value or a React binding of that value:",
    "    react-roblox checks for a binding on any key before assigning the",
    "    property (RobloxComponentProps.applyProp).",
    "",
    "    The `[any]: any` indexer is what makes the keys that are not strings",
    "    acceptable: [React.Event.X], [React.Change.X] and [React.Tag] (a",
    "    space-separated string of tags). React's own string keys -- key, ref,",
    "    children, __self, __source -- need no indexer, because an undeclared",
    "    string key passes either way: Luau runs no excess-property check unless",
    "    a type asks for one, and this one cannot ask without rejecting the",
    "    markers above. A component's own props can: `[string]: nil`.",
    "",
    "    The indexer costs exactly one thing, measured rather than assumed:",
    "    reading an undeclared field stops being an error. Type checking on the",
    "    declared props survives it untouched.",
];

pub fn emit(surface: &Surface, style: &Style) -> Emitted {
    let mut out = String::new();
    let mut properties = 0;
    let tab = style.indent.as_str();

    out.push_str("--!strict\n");
    out.push_str("--[[\n");
    out.push_str("    DO NOT EDIT BY HAND.\n");
    out.push('\n');
    out.push_str("    Generated by react-luau-props from Roblox's own API dump.\n");
    out.push_str("    https://github.com/rbx-forge/react-luau-props\n");
    out.push('\n');
    for line in INDEXER_NOTE {
        out.push_str(line);
        out.push('\n');
    }
    out.push_str("]]\n\n");

    let _ = writeln!(
        out,
        "local ReplicatedStorage = game:GetService(\"ReplicatedStorage\")\n"
    );
    let _ = writeln!(out, "local React = require({})\n", style.require_path);

    for class in &surface.classes {
        let _ = writeln!(out, "export type {} = {{", class.name);

        let mut last_owner: Option<&str> = None;
        for property in &class.properties {
            if last_owner != Some(property.owner.as_str()) {
                if last_owner.is_some() {
                    out.push('\n');
                }
                let _ = writeln!(out, "{tab}-- {}", property.owner);
                last_owner = Some(property.owner.as_str());
            }

            let mut note = String::new();
            if property.deprecated {
                note.push_str(" -- deprecated");
            }
            if property.hidden {
                note.push_str(if note.is_empty() {
                    " -- hidden"
                } else {
                    ", hidden"
                });
            }

            let _ = writeln!(
                out,
                "{tab}{}: {}? | React.Binding<{}>?,{}",
                property.name, property.luau, property.luau, note
            );
            properties += 1;
        }

        let _ = writeln!(out, "\n{tab}[any]: any,");
        out.push_str("}\n\n");
    }

    out.push_str("return nil\n");

    Emitted {
        source: out,
        classes: surface.classes.len(),
        properties,
    }
}
